
ARG USER
ARG UID
ARG GID
ARG REQUIREMENTS_FILE
ARG PYTHON_REQUIREMENTS_FILE
ARG ROS_DISTRO
ARG OS_CODE_NAME

FROM ros:${ROS_DISTRO}-ros-core-${OS_CODE_NAME} AS adore_cli_core

ARG USER
ARG UID
ARG GID
ARG REQUIREMENTS_FILE="requirements.adore_cli_core.ubuntu.system"
ARG PYTHON_REQUIREMENTS_FILE="requirements.adore_cli_core.pip3"

COPY docker/files/${REQUIREMENTS_FILE} /tmp
WORKDIR /tmp
ENV DEBIAN_FRONTEND=noninteractive
RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
    --mount=target=/var/cache/apt,type=cache,sharing=locked \
    rm -f /etc/apt/apt.conf.d/docker-clean && \
    rm /var/lib/dpkg/info/libc-bin.* || true && \
    apt-get update && \
    apt-get install --no-install-recommends -y $(sed '/^#/d' ${REQUIREMENTS_FILE} | sed '/^$/d')

COPY docker/files/${PYTHON_REQUIREMENTS_FILE} /tmp
RUN --mount=type=cache,target=/root/.cache/pip \
    python3 -m pip install -r ${PYTHON_REQUIREMENTS_FILE}

RUN useradd -m ubuntu
RUN userdel --remove ubuntu
RUN rm -rf /home/ubuntu
RUN useradd --create-home ${USER}
RUN cat /etc/passwd && usermod -u ${UID} ${USER} && groupmod -g ${GID} ${USER}
RUN chown -R ${UID}:${GID} $$HOME | true

ARG ZSH_CUSTOM=/home/${USER}/.oh-my-zsh/custom

RUN wget https://github.com/mikefarah/yq/releases/download/v4.2.0/yq_linux_arm64 -O /usr/local/bin/yq 
RUN chmod +x /usr/local/bin/yq

USER ${USER}
WORKDIR /home/${USER}

RUN zsh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"



USER root
COPY docker/files/.zshrc /home/${USER}
RUN chown -R ${UID}:${GID} /home/${USER}

RUN echo "${USER} ALL = NOPASSWD : /usr/sbin/rsyslogd, /usr/bin/apt-get, /usr/bin/apt, /usr/bin/python3, /usr/bin/apt-file, /usr/bin/apt-cache, /usr/bin/aptitude" >> /etc/sudoers

RUN mkdir -p /var/log/ros2 && \
    chmod -R 777 /var/log/ros2
COPY docker/files/rsyslog.conf /etc/rsyslog.conf 

RUN mkdir -p /tmp/adore

WORKDIR /tmp/adore


USER ${USER}

ENV PATH="/usr/lib/ccache:${PATH}"


#FROM adore_cli_core_base AS adore_cli_core

ARG USER
ARG REQUIREMENTS_FILE="requirements.adore_cli_core_x11_display.ubuntu.system"

USER root
COPY docker/files/${REQUIREMENTS_FILE} /tmp
WORKDIR /tmp
ENV DEBIAN_FRONTEND=noninteractive
RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
    --mount=target=/var/cache/apt,type=cache,sharing=locked \
    rm -f /etc/apt/apt.conf.d/docker-clean && \
    rm /var/lib/dpkg/info/libc-bin.* || true && \
    apt-get update && \
    apt-get install --no-install-recommends -y $(sed '/^#/d' ${REQUIREMENTS_FILE} | sed '/^$/d')

#CMD exec /bin/bash -c "trap : TERM INT; [ -f /tmp/adore/setup.sh ] && source /tmp/adore/setup.sh; sudo rsyslogd -n & sleep infinity & wait"
#CMD exec /bin/bash -c "trap : TERM INT; sudo rsyslogd -n & sleep infinity & wait"

COPY docker/files/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

USER $USER
WORKDIR /tmp/adore

ENTRYPOINT ["/entrypoint.sh"]
